### ISSUE TITLE
module 'signal' has no attribute 'SIGPIPE' on jupyter notebook , python 3.6 on windows 

### ISSUE THREAD

**Issue by salmacmpeg** [t2mune/mrtparse#18]
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\salmacmp\AppData\Local\Temp\pip-req-build-fs_0nxwc\setup.py", line 32, in <module>
        import mrtparse
      File "C:\Users\salmacmp\AppData\Local\Temp\pip-req-build-fs_0nxwc\mrtparse\__init__.py", line 31, in <module>
        signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    AttributeError: module 'signal' has no attribute 'SIGPIPE'

**Comment by salmacmpeg** [comment]
solved , by removing line 30, 31 from init.py file

**Comment by t2mune** [comment]
Thank you for letting me know about this issue !

[SIGPIPE is necessary except for Windows, so I changed not to handle SIGPIPE if it doesn't exist.](https://github.com/t2mune/mrtparse/commit/15493116e1dba4ee419daefc9413eb3ba0972926)

**Comment by t2mune** [comment]
I will close this issue, but if there are other issues, please let me know :exclamation:
