### ISSUE TITLE
Error parsing RIPE MRT data

### ISSUE THREAD

**Issue by nkukard** [t2mune/mrtparse#26]
I must be doing something wrong, I'm using the latest git checkout.

I am trying to pull out all the Cogent routing information for AS174...
```
wget http://data.ris.ripe.net/rrc00/2020.11/bview.20201101.0000.gz
examples/mrt2exabgp.py -p 174 -s -A bview.20201111.0000.gz
```

The error I'm getting is this...
```
$ examples/mrt2exabgp.py -p 174 -s -A bview.20201111.0000.gz
Traceback (most recent call last):
  File "examples/mrt2exabgp.py", line 514, in <module>
    main()
  File "examples/mrt2exabgp.py", line 511, in main
    conv_format(args, flags, d)
  File "examples/mrt2exabgp.py", line 185, in conv_format
    print_route_td(args, params, m.data)
  File "examples/mrt2exabgp.py", line 250, in print_route_td
    line += get_bgp_attr(args, params, m, attr)
  File "examples/mrt2exabgp.py", line 397, in get_bgp_attr
    path_seg = attr['as_path'][0]
KeyError: 'as_path'
```

Any help would be greatly appreciated!

**Comment by t2mune** [comment]
Hi,

Thank you for reporting this issue.
I fixed it, so could you try again?
9c545fe1c2554feabf3efde1f122f730437ecda0

"mrt2exabgp.py" convert only first entry for each prefix by default, so it's better to specify the "-a" option.

```
examples/mrt2exabgp.py -a -p 174 -s -A bview.20201111.0000.gz
```

**Comment by nkukard** [comment]
Confirmed working, thanks for the great work man!
