### ISSUE TITLE
AttributeError: 'Reader' object has no attribute 'mrt'

### ISSUE THREAD

**Issue by aweher** [t2mune/mrtparse#34]
### System Desc
```
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu4-noarch:printing-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

$ python -V
Python 3.10.12
$ pip3 freeze | grep mrt
mrtparse==2.2.0
```

### Error reported

```python
$ mrt2exabgp -P latest-bview.gz 
#!/usr/bin/env python

import sys
import time

msgs = [
Traceback (most recent call last):
  File "/usr/bin/mrt2exabgp", line 498, in <module>
    main()
  File "/usr/bin/mrt2exabgp", line 495, in main
    conv_format(args, flags, d)
  File "/usr/bin/mrt2exabgp", line 192, in conv_format
    m = m.mrt
        ^^^^^
AttributeError: 'Reader' object has no attribute 'mrt'
```

**Comment by t2mune** [comment]
It appears that you are using a script for an older version. Could you please download the following script and try again?
[https://github.com/t2mune/mrtparse/blob/master/examples/mrt2exabgp.py](https://github.com/t2mune/mrtparse/blob/master/examples/mrt2exabgp.py)

**Comment by t2mune** [comment]
Did it work?
